CREATE TABLE public.planos_de_aula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    tema_aula TEXT NOT NULL,
    ano_escolar TEXT NOT NULL,
    introducao_ludica TEXT,
    objetivo_bncc TEXT,
    passo_a_passo TEXT,
    rubrica_avaliacao TEXT
);

COMMENT ON TABLE public.planos_de_aula IS 'Armazena os planos de aula gerados pela IA.';